/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package imageconverter;

import imageconverter.model.*;

public class App {
    public static void main(String[] args) {
        Arguments arguments = ArgumentsParser.parse(args);
        try {
            ImageConverter.convertImage(arguments);
        } catch (Exception e) {
            System.out.println(e);
            System.exit(1);
        }
    }
}
